name: 'text-summarizer-api'

services:

  web:
    build:
      context: ./project
      dockerfile: dev.Dockerfile
    container_name: dev-api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/app:/opt/project/app
      - ./project/tests:/opt/project/tests
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_dev       
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test  

  web-db:
    build:
      context: ./project/db
      dockerfile: db.Dockerfile
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
